# Generated by Django 2.1.7 on 2019-03-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190308_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount_cur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='money',
            name='amount_ru',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='money',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Member'),
        ),
    ]
