# Generated by Django 2.1.7 on 2019-03-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190308_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
    ]
