# Generated by Django 2.1 on 2019-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20190308_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount_cur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='money',
            name='amount_ru',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
