# Generated by Django 2.1.7 on 2019-03-28 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20190328_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='money',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
