# Generated by Django 2.1.7 on 2019-03-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20190328_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='amount_ru',
        ),
    ]
