# Generated by Django 2.1.7 on 2019-03-29 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_remove_money_amount_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount_cur',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Сумма (в валюте)'),
        ),
        migrations.AlterField(
            model_name='money',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='money',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='money',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='money',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='money',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Member', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='money',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Sign', verbose_name='+\\-'),
        ),
    ]
